### ISSUE TITLE
linear-gradient not working in FF

### ISSUE THREAD

**Issue by DerOetzi** [codler/jQuery-Css3-Finalize#19]
I have problems to get linear-gradient working on all of my firefox-browsers.

I have tested on WIN7 FF14 and WIN7 FF15 and on Ubuntu 12.04 FF 15.

I have made a fiddle which works fine on Chrome and IE 8+9 but not on any of my FF.

http://jsfiddle.net/PCYXT/1/

**Comment by DerOetzi** [comment]
Oh i forgot with css3finalize 2.5 it has worked fine. Error occured after upgrading to version 3.1

**Comment by codler** [comment]
Thanks for reporting!

Yes Im aware, I planned alitte ahead. linear-gradient in v3.1 will work in FF 16 and FF16 will release 9th october.

http://browsershots.org/screenshots/bcf0b2001de0336a775426b0f0a9c95c

so you could use v2.5 meanwhile or w8 to 9th october.

**Comment by codler** [comment]
or if you want a patch, 
replace this line https://github.com/codler/jQuery-Css3-Finalize/blob/v3.1/jquery.css3finalize.js#L369
`} else if (currentPrefix == 'webkit') {`
with 
`} else if (currentPrefix == 'webkit' || currentPrefix == 'moz') {`

**Comment by DerOetzi** [comment]
Thanks for the fast reply i added the patch now. But I wonder if there should be the possibility that css3finalize v3.1 is working for those who don't update there firefox.

**Comment by codler** [comment]
Firefox have auto update and in less than 1month from FF release almost everyone have the latest version http://gs.statcounter.com/#browser_version-ww-weekly-201227-201236

**Comment by DerOetzi** [comment]
But what is with the user of Long Term Support versions of firefox, which are mainly companies? Those will not see the linear-gradients. I think this should be not very difficult to add the support the patched line you have written above should look something like this:

} else if (currentPrefix == 'webkit' || (currentPrefix == 'moz' && parseInt($.browser.version) < 16)) {

**Comment by codler** [comment]
Do you know when next LTS version will come?

**Comment by codler** [comment]
Next Firefox ESR version will come when Firefox 17 releases which are on the 20th November.
https://wiki.mozilla.org/Enterprise/Firefox/ExtendedSupport:Proposal#Proposal
