### ISSUE TITLE
masks and appearance

### ISSUE THREAD

**Issue by ianstormtaylor** [codler/jQuery-Css3-Finalize#3]
Two other rules it would be nice to have support for: `-webkit-mask` and `-webkit-appearance`.

**Comment by ianstormtaylor** [comment]
In other words just `mask (and its shorthands)` (http://www.webkit.org/blog/181/css-masks/) and `appearance` for every renderer.

**Comment by codler** [comment]
I have added those properties now, thanks!

https://github.com/codler/jQuery-Css3-Finalize/commit/f665514b39efc8e4fd733a2282760ef212c1e58e

**Comment by ianstormtaylor** [comment]
Awesome! So quick.

Dumb question but will the github link in the document always point to the newest version (as in do I not have to touch anything to get the upgrade?)

**Comment by codler** [comment]
yes, the static file ( https://github.com/codler/jQuery-Css3-Finalize/raw/master/static/jquery.css3finalize-latest.min.js ) in github will always be the latest. =)

**Comment by ianstormtaylor** [comment]
The `mask` isn't working for `-webkit` at least. `appearance` is now though.

**Comment by codler** [comment]
It works, here is an example http://jsfiddle.net/aK4Ts/

**Comment by ianstormtaylor** [comment]
Here's my live example: http://ianstormtaylor.com/experiments/babyname/

The `footer` should be getting the same fading gradient mask the `header` is getting, but it's not. Not sure what I'm doing wrong. I haven't been using the `box-image` syntax though.

**Comment by codler** [comment]
Your code is correct. 
I found out why mask didnt work. It is a strange bug. I use <code>document.createElement('style').style.mask</code> to validate if a css property is supported and strangely webkit says it is valid. Ill try to fix this.

**Comment by codler** [comment]
This bug is now patched.

https://github.com/codler/jQuery-Css3-Finalize/commit/b2a89ddba6544449d4d0e456ff2afa74c1b78841

**Comment by ianstormtaylor** [comment]
Thanks! Awesome plugin... going into my default for every new project hah
