### ISSUE TITLE
Gradients

### ISSUE THREAD

**Issue by ianstormtaylor** [codler/jQuery-Css3-Finalize#4]
Would be cool if it parsed `gradient`s from what the spec says (http://dev.w3.org/csswg/css3-images/#gradients) and translated them to the appropriate gradient for the browser. It would just require some logic to convert to `-webkit-gradient` because `-moz-gradient` is the same as the spec I believe.

**Comment by codler** [comment]
<code>-webkit-gradient</code> differs too much compare to <code>-moz-linear-gradient</code> so it would require very much work to convert. but webkit will add <code>-webkit-linear-gradient</code>. It currently is implemented in Chrome beta 10. When <code>-webkit-linear-gradient</code> has come to the stable version, then it will be much easier and ill try to make the convert.
http://www.webkit.org/blog/1424/css3-gradients/

**Comment by codler** [comment]
This is undocumented but css3finalize do partial support linear-gradient
<code>
background-image: linear-gradient(#ffffff, #e5e5e5);
</code>
This only works on property background-image and linear-gradient only takes 2 parameters as show above. It must be hexadecimal and have 6 signs (cant be 3).
One more special is that this will render in Opera too! =)

**Comment by codler** [comment]
https://github.com/codler/jQuery-Css3-Finalize/commit/8e4fda4e49368d53dccbe29c041513b02bcfd66e
