### ISSUE TITLE
Media Queries

### ISSUE THREAD

**Issue by ianstormtaylor** [codler/jQuery-Css3-Finalize#5]
Another issue is for parsing vendor specific styles inside of Media Queries. They would need to added into Media Queries again in the inject style.

**Comment by ianstormtaylor** [comment]
As it stands now, all changes to vendor-prefixed items in Media Queries have to have `!important` so they they override the injected vendor-prefixed styles.

**Comment by ianstormtaylor** [comment]
Did I close this by accident?

**Comment by codler** [comment]
I think this commit will fix this issue :P

https://github.com/codler/jQuery-Css3-Finalize/commit/a6a97ffb70af1333d293712ba392855b6f982eb1

**Comment by ianstormtaylor** [comment]
Yup sure did thanks!
