### ISSUE TITLE
Transitioning Transforms

### ISSUE THREAD

**Issue by ianstormtaylor** [codler/jQuery-Css3-Finalize#6]
Another similar problem to the Gradient one of parsing inside a vendor-specific declaration is when dealing with transitions:

`transition: tranform 1s, opacity 1s;`

Should ideally cover both:
    -webkit-transition: -webkit-transform 1s, opacity 1s;
    -moz-transition: -moz-transform 1s, opacity 1s;`

In addition the alternate syntax:
`transition-property: transform, opacity;`
would need to be checked as well.

**Comment by codler** [comment]
Fixed!

https://github.com/codler/jQuery-Css3-Finalize/commit/00df1e8eeb546b34782b97ddfdb4f7bd31a7d083

Thanks for reporting the issue!
