### ISSUE TITLE
IE8 crashes using CSS3 Finalize 1.43

### ISSUE THREAD

**Issue by Rikezenho** [codler/jQuery-Css3-Finalize#7]
Hello codler,
First, congratulations for your job, it's a really useful script.

But since i started to use 1.43 version, i checked that it was causing a serious crash in IE8 (without add-ons, default settings). I didn't test another IE version, but i checked the problem in IE8.

I'll be so thankful if you could solve it. Sorry by my bad english, i'm brazilian.

**Comment by codler** [comment]
Thank you.

I tested v1.43 and v1.44 on IE8 now both local and online and it didnt crash on my computer. 
Could you provide some more details? Do you have the site online or could send me a test case? What css styles did the site have?

**Comment by Rikezenho** [comment]
Internet Explorer says "can't reload the tab" and stops loading "after 2 attempts, to prevent infinite loop".
When i remove the script, the page reloads normally.

Using the previous version of the script the problem don't occurs.

**Comment by codler** [comment]
That wasnt much of help for debugging. What code (css, javascript) do the site have?

**Comment by codler** [comment]
http://css-tricks.com/13414-seriously-just-make-a-jsfiddle/

Unless I can reproduce the problem or other have same problem Ill close issue.
