### ISSUE TITLE
$.isNaN() undocumented

### ISSUE THREAD

**Issue by dmethvin** [codler/jQuery-Css3-Finalize#9]
The undocumented $.isNaN() method is being removed from jQuery 1.7 and replaced by a documented $.isNumeric (which has the opposite meaning).

**Comment by codler** [comment]
Thanks for the heads up!

**Comment by codler** [comment]
Fixed.
https://github.com/codler/jQuery-Css3-Finalize/commit/c0cbc40c3dac5dc5eb8033de8e87b6e7371622be

**Comment by runtalan** [comment]
I wish this was documented in the changelog!
